apiVersion: v1
kind: Service
metadata:
  name: primary-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 6379
      port: 6379
      nodePort: 30001
  selector:
    name: redis-primary

---

apiVersion: v1
kind: Service
metadata:
  name: secondary-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 6379
      port: 6379
      nodePort: 30002
  selector:
    name: redis-secondary

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-primary
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: redis-primary
  template:
    metadata:
      labels:
        name: redis-primary
    spec:
      subdomain: primary
      containers:
        - name: redis
          image: redis:latest
          command:
            - "redis-server"
          args:
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-secondary
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-secondary
  template:
    metadata:
      labels:
        name: redis-secondary
    spec:
      subdomain: replica
      containers:
        - name: redis
          image: redis:latest
          command:
            - "redis-server"
          args:
            - "--slaveOf"
            - "primary-service.default.svc.cluster.local"
            - "6379"
            - "--protected-mode"
            - "no"
          ports:
            - containerPort: 6379


