apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: 'bitnami/kafka:latest'
          ports:
            - containerPort: 9092
              protocol: TCP
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: 'zk-cs:2181'
            - name: KAFKA_CFG_ADVERTISED_LISTNERS
              value: 'PLAINTEXT://127.0.0.1:9092'
            - name: KAFKA_CFG_LISTENERS
              value: 'PLAINTEXT://:9092'
            - name: KAFKA_BROKER_ID
              value: '1'
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname

