apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: schema-registry
    app.kubernetes.io/instance: release
    app.kubernetes.io/name: schema-registry-svc
  name: schema-registry-svc
  namespace: default
spec:
  ports:
  - port: 8081
    name: reg-client
    targetPort: reg-client
  selector:
    app.kubernetes.io/component: schema-registry
    app.kubernetes.io/instance: release
    app.kubernetes.io/name: schema-registry

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: schema-registry
    app.kubernetes.io/instance: release
    app.kubernetes.io/name: schema-registry
  name: schema-registry
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: schema-registry
      app.kubernetes.io/instance: release
      app.kubernetes.io/name: schema-registry
  template:
    metadata:
      labels:
        app.kubernetes.io/component: schema-registry
        app.kubernetes.io/instance: release
        app.kubernetes.io/name: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry:7.1.0
        ports:
        - containerPort: 8081
          name: reg-client
          protocol: TCP
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: kafka-svc-headless.default.svc.cluster.local:9092
